FROM demiddleday3_jupyter:latest

MAINTAINER yoon, koock <deep-learning@kakao.com>

COPY ./ /root/DE-middle/redis/producer/

WORKDIR /root/DE-middle/redis/producer/

EXPOSE 8888

ENTRYPOINT jupyter notebook --allow-root --ip=0.0.0.0 --port=8888 --no-browser