FROM ubuntu:18.04

MAINTAINER yoon, koock <deep-learning@kakao.com>

WORKDIR /root/DE-middle/

RUN printf "Acquire::http::Pipeline-Depth 0;\nAcquire::http::No-Cache true;\nAcquire::BrokenProxy true;" > /etc/apt/apt.conf.d/99fixbadproxy
RUN sed -i 's/archive.ubuntu.com/kr.archive.ubuntu.com/g' /etc/apt/sources.list
RUN apt update
RUN apt install -y python3.7
RUN apt install -y python3-dev python3-pip

RUN alias python=python3.7
RUN alias pip=pip3

RUN pip3 install jupyter

RUN jupyter notebook --generate-config --allow-root

RUN echo "c.NotebookApp.password = u'sha1:6a3f528eec40:6e896b6e4828f525a6e20e5411cd1c8075d68619'" >> /root/.jupyter/jupyter_notebook_config.py
