version: '2'

services:
  redis-producer:
    build:
      context: producer
      dockerfile: ./Dockerfile.yml
    network_mode: "host"
    ports:
      - 8888:8888

  redis-consumer:
    build:
      context: consumer
      dockerfile: ./Dockerfile.yml
    network_mode: "host"
    ports:
      - 8889:8889

  redis:
    image: redis:5.0.3
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    network_mode: "host"
    ports:
        - 6379:6379
    volumes:
        - /root/docker/redis-5.0.3/data:/data
    command: redis-server
    environment:
      - REDIS_PASSWORD=password123

